#%RAML 0.8
title: Server Catalog
version: v1
baseUri: http://servercatalog-env.elasticbeanstalk.com/api/v1/

/servers: 
  post:
    description: Create a Server record. It can create apps or associate exists apps to Server record
    body:
      application/json: 
        example: |
          {
            "hostname": "Game Server",
            "apps": [
                  {
                    "name": "Game 1",
                    "owner": "joao@gmail.com"
                  },
                  {
                    "id": 2
                  }
                ]
          } 
    responses:
      201:
        headers:
          Location:
  
  get:
    description: Get last 10 updated servers
    queryParameters:
      offset:
      max:
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "id": 1,
                  "hostname": "Game Server X",
                  "apps": [
                    {
                      "id": 1,
                      "name": "Game 1x",
                      "owner": "joao@gmail.com"
                    }
                  ]
                 }
                 //,{...},{...}
              ]
  /{id}/:
    get:
      description: Get server record with {id}
      responses:
        200:
          body:
            application/json: 
              example: |
                {
                  "id": 1,
                  "hostname": "Game Server X",
                  "apps": [
                    {
                      "id": 1,
                      "name": "Game 1x",
                      "owner": "joao@gmail.com"
                    }
                  ]
                }
        404:
          description: Server not found!
          body:
            application/json: 
              example: |
                {msg: "{id} Not found!"}
    put:
      description: Update server record
      body:
        application/json: 
          example: |
            {            
              "hostname": "Game Server X",
              "apps": [
                    {
                      "id": 1,
                      "name": "Game 1x",
                      "owner": "joao@gmail.com"
                    }
              ]
            } 
      responses:
        200:
          description: Server updated!
        404:
          description: Server not found!
          body:
            application/json: 
              example: |
                {"msg": "{id} not found"}
      
    delete:
      description: Delete a server record
      responses:
        200:
          description: Deleted with success!
        404: 
          description: Server not found!
          
/applications:
  get:
    description: List Applications
    queryParameters:
      offset:
      max:
    responses:
      200:
        body:
          application/json:
            example: |
              [{"id":1, "name": "Game X", "owner": "lucas@gmail.com"},
               {"id":2, "name": "Game L", "owner": "jose@gmail.com"}]
              
  post:
    description: Create Application record
    body:
      application/json:
        example: |
         {
            "name": "Game 1.1",
            "owner": "jose@gmail.com"
         } 
    responses:
      201:
        headers:
          Location:
  /{id}/:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
               {
                "id" : 1,
                "name": "Game 1.1",
                "owner": "jose@gmail.com"
               }
        404:
          description: "Not found!"
    put:
      description: Create Application record
      body:
        application/json:
          example: |
           {
            "name": "Game X1",
            "owner": "joao@gmail.com"
           } 
      responses:
        200:
          description: Application updated!
                            
    delete:
      description: "Delete a Application record with {id}"
      responses:
        200:
          description: Deleted!
        404:
          description: Application not found!
      